### ISSUE TITLE
Unable to view HTML5 report

### ISSUE THREAD

**Issue by Floraxio** [esnext-coverage/esnext-coverage-format-html#3]
Unable to view HTML5 report

After launching the tests, it is not possible to view the html report

![image](https://cloud.githubusercontent.com/assets/1224004/23205852/b450007e-f8eb-11e6-84fb-a1bbfe26b296.png)

thx a lot.

**Comment by olegskl** [comment]
Which version of esnext-coverage-format-html are you using? Please upgrade to 0.0.7, this should solve the issue.

**Comment by Floraxio** [comment]
This is working, thanx you :-)
